print("Hello world!")
name=input("enter my name:")
print("Hello "+name+"!")
print("   /|")
print("  / |")
print(" /  |")
print("/___|")

# variables

character_name="sakshi"
character_hobby=" traveling"
print("There is a lady whose name "+ character_name +",")
print("she loves" +character_hobby+ ",")
character_name=" Radha"
print("she is so elegant "+character_name+"!")
print("she badly want to build a robot which can do all her work just on her one command.")


# functions
N=input("My name :")
print(N.upper())
print(len(N))
phrase="DISNEY RADHA RANI"
print(phrase.replace("DISNEY","PYARI JU"))

# maths function

from math import *
my_num=5
print(pow(2,5))
print(max(6,100))
print(min(6,100))
print(round(7.99))
print(sqrt(100))
print(floor(3.7))
